In [39]:
#Exercício 1
import numpy as np

def Assembly(conec, C):
    nv = 5
    nc = len(C)
    A = np.zeros(shape=(nv,nv))
    for k in range(nc):
        n1 = conec[k, 0]
        n2 = conec[k, 1]
        
        A[n1-1, n1-1] += C[k]
        A[n1-1, n2-1] += -C[k]
        A[n2-1, n1-1] += -C[k]
        A[n2-1, n2-1] += C[k]

    return A

conec = np.zeros(shape=(7,2), dtype=int)

conec[0] = [1,2]
conec[1] = [2,3]
conec[2] = [3,4]
conec[3] = [4,5]
conec[4] = [5,2]
conec[5] = [5,3]
conec[6] = [5,1]

C = [2,2,1,2,1,2,2]
print(Assembly(conec, C))

[[ 4. -2.  0.  0. -2.]
 [-2.  5. -2.  0. -1.]
 [ 0. -2.  5. -1. -2.]
 [ 0.  0. -1.  3. -2.]
 [-2. -1. -2. -2.  7.]]


In [53]:
#Exercício 2

import numpy as np

def Assembly(conec, C):
    nv = 5
    nc = len(C)
    A = np.zeros(shape=(nv,nv))
    for k in range(nc):
        n1 = conec[k, 0]
        n2 = conec[k, 1]
        
        A[n1-1, n1-1] += C[k]
        A[n1-1, n2-1] += -C[k]
        A[n2-1, n1-1] += -C[k]
        A[n2-1, n2-1] += C[k]

    return A

def SolveNetwork(conec, natm, nB, QB):
    Atilde = Assembly(conec, [2,2,1,2,1,2,2])
    Atilde[natm-1, :] = 0
    Atilde[natm-1, natm-1] = 1
    b = np.zeros(shape=5)
    b[nB-1] = QB
    pressure = np.linalg.solve(Atilde, b)
    return pressure

conec = np.zeros(shape=(7,2), dtype=int)

conec[0] = [1,2]
conec[1] = [2,3]
conec[2] = [3,4]
conec[3] = [4,5]
conec[4] = [5,2]
conec[5] = [5,3]
conec[6] = [5,1]

pressao = SolveNetwork(conec, 3, 1, 3)

print(pressao)

[1.39772727e+00 6.81818182e-01 1.11022302e-16 4.09090909e-01
 6.13636364e-01]
